### ISSUE TITLE
tests/test4.kdbx cannot be opened with KeepassXC nor with Windows Keepass

### ISSUE THREAD

**Issue by infeeeee** [libkeepass/pykeepass#330]
KeepassXC drops this error:

```
Error while reading the database: Invalid inner header binary size
```

The problem is in this commit: 8eed21100693842bbc7ad93527c9d6670cdc0070

test3.kdbx from the same commit is not affected.

Older version can be opened with both KeepassXC and Windows Keepass, this version works fine: https://github.com/libkeepass/pykeepass/blob/199cf0ebfa8bfd3dd3e79dfd56e69f18a9da8428/tests/test4.kdbx

**Comment by Evidlo** [comment]
Thanks for reporting this.  It looks like when I modified `test4.kdbx` to have a binary with no data, I mistakenly modified the bytes directly with

    kp.kdbx.body.payload.inner_header.binary[0].data = b''

But KDBX4 binary elements must contain at least one byte that denotes whether the binary is protected or not, so this is invalid.  pykeepass didn't catch this because we don't check the contents of binary data during database parsing.

Anyway, this mistake isn't possible as long as you are using the pykeepass api.  I will fix the test database.
